import datetime
import json
import os

timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
INPUT_JSON = "building_model.json"
OUTPUT_FILENAME = f"model_FIXED_{timestamp}.idf"
OUTPUT_PATH = os.path.join("simulation", OUTPUT_FILENAME)


def run_conversion():
    print(f"\n[START] 启动转换程序... 时间: {timestamp}")
    if not os.path.exists(INPUT_JSON):
        print("❌ 找不到 JSON 文件!")
        return

    with open(INPUT_JSON, 'r', encoding="utf-8") as f:
        data = json.load(f)

    idf_content = f"! Generated by EnergyAgent at: {timestamp}\n"

    idf_content += """
    Version, 25.1;
    Timestep, 6;
    GlobalGeometryRules, UpperLeftCorner, CounterClockwise, Relative;
    Building, My Building, 0.0, City, 0.04, 0.4, FullInteriorAndExterior, 25, 6;
    SimulationControl, No, No, No, Yes, Yes;
    """
    loc = data.get("Location", {})
    idf_content += f"""
    Site:Location,
        {loc.get("City", "Unknown")},
        {loc.get("latitude", 0.0)},
        {loc.get("longitude", 0.0)},
        8.0, 50.0;
    """

    cons_info = data.get("Construction", {})
    u_val = cons_info.get("u_value", 1.0)
    insulation_thick = 0.1 if u_val < 0.6 else 0.05
    idf_content += f"""
    Material, Concrete_Layer, MediumRough, 0.2, 1.7, 2300, 1000;
    Material, Insulation_Layer, Smooth, {insulation_thick}, 0.04, 30, 1200;
    Construction, Wall_Cons, Concrete_Layer, Insulation_Layer;
    Construction, Floor_Cons, Concrete_Layer;
    Construction, Roof_Cons, Concrete_Layer, Insulation_Layer;
    """
    sch_data = data.get("Schedule", {})
    if "Residential" in str(sch_data):
        sch_values = "Through: 12/31, For: AllDays, Until: 08:00, 1.0, Until: 18:00, 0.0, Until: 24:00, 1.0;"
    else:
        sch_values = "Through: 12/31, For: AllDays, Until: 08:00, 0.0, Until: 18:00, 1.0, Until: 24:00, 0.0;"

    idf_content += f"""
    ScheduleTypeLimits, Any Number;
    Schedule:Compact, Occupancy_Sch, Any Number, {sch_values}
    """
    geo_data = data.get("Geometry", {})
    zones = geo_data.get("Zones", [])
    print(f"-> 生成 {len(zones)} 个房间的几何体...")

    for i, zone_name in enumerate(zones):
        x = i * 10
        idf_content += f"""
    ! --- Zone: {zone_name} ---
    Zone, {zone_name}, 0, {x}, 0, 0;

    BuildingSurface:Detailed,
        {zone_name}_Floor,      !- Name
        Floor,                  !- Surface Type
        Floor_Cons,             !- Construction Name
        {zone_name},            !- Zone Name
        Ground,                 !- Outside Boundary Condition
        ,                       !- Outside Boundary Condition Object (Empty)
        NoSun,                  !- Sun Exposure
        NoWind,                 !- Wind Exposure
        1.0,                    !- View Factor to Ground
        4,                      !- Number of Vertices
        10, 10, 0,
        0, 10, 0,
        0, 0, 0,
        10, 0, 0;

    BuildingSurface:Detailed,
        {zone_name}_Roof,       !- Name
        Roof,                   !- Surface Type
        Roof_Cons,              !- Construction Name
        {zone_name},            !- Zone Name
        Outdoors,               !- Outside Boundary Condition
        ,                       !- Object
        SunExposed,             !- Sun Exposure
        WindExposed,            !- Wind Exposure
        0.0,                    !- View Factor
        4,                      !- Number of Vertices
        10, 10, 3,
        10, 0, 3,
        0, 0, 3,
        0, 10, 3;

    BuildingSurface:Detailed,
        {zone_name}_Wall_S,     !- Name
        Wall,                   !- Surface Type
        Wall_Cons,              !- Construction Name
        {zone_name},            !- Zone Name
        Outdoors,               !- Outside Boundary Condition
        ,                       !- Object
        SunExposed,             !- Sun Exposure
        WindExposed,            !- Wind Exposure
        0.5,                    !- View Factor
        4,                      !- Number of Vertices
        0, 0, 3,
        0, 0, 0,
        10, 0, 0,
        10, 0, 3;

    BuildingSurface:Detailed,
        {zone_name}_Wall_N,     !- Name
        Wall,                   !- Surface Type
        Wall_Cons,              !- Construction Name
        {zone_name},            !- Zone Name
        Outdoors,               !- Outside Boundary Condition
        ,                       !- Object
        SunExposed,             !- Sun Exposure
        WindExposed,            !- Wind Exposure
        0.5,                    !- View Factor
        4,                      !- Number of Vertices
        10, 10, 3,
        10, 10, 0,
        0, 10, 0,
        0, 10, 3;

    BuildingSurface:Detailed,
        {zone_name}_Wall_E,     !- Name
        Wall,                   !- Surface Type
        Wall_Cons,              !- Construction Name
        {zone_name},            !- Zone Name
        Outdoors,               !- Outside Boundary Condition
        ,                       !- Object
        SunExposed,             !- Sun Exposure
        WindExposed,            !- Wind Exposure
        0.5,                    !- View Factor
        4,                      !- Number of Vertices
        10, 0, 3,
        10, 0, 0,
        10, 10, 0,
        10, 10, 3;

    BuildingSurface:Detailed,
        {zone_name}_Wall_W,     !- Name
        Wall,                   !- Surface Type
        Wall_Cons,              !- Construction Name
        {zone_name},            !- Zone Name
        Outdoors,               !- Outside Boundary Condition
        ,                       !- Object
        SunExposed,             !- Sun Exposure
        WindExposed,            !- Wind Exposure
        0.5,                    !- View Factor
        4,                      !- Number of Vertices
        0, 10, 3,
        0, 10, 0,
        0, 0, 0,
        0, 0, 3;
    """

    # ==========================================
    # 6. HVAC
    # ==========================================
    hvac_data = data.get("HVAC", {})
    sys_type = hvac_data.get("SystemType", "IdealLoads")
    applied_zones = hvac_data.get("Applied_Zones", [])

    idf_content += """
    HVACTemplate:Thermostat, Main_Thermostat, Occupancy_Sch, 20, Occupancy_Sch, 26;
    """

    for zone_name in applied_zones:
        if "VRF" in sys_type:
            idf_content += (
                f"HVACTemplate:Zone:VRF, {zone_name}, Main_Thermostat, Auto, Auto;\n"
            )
        elif "VAV" in sys_type:
            idf_content += f"HVACTemplate:Zone:VAV, {zone_name}, Main_Thermostat, Main_VAV_Sys, Auto, Auto, Auto;\n"
    if "VRF" in sys_type:
        idf_content += """
    HVACTemplate:System:VRF, Main_VRF_Sys, Auto, Auto, Auto;
    """
    elif "VAV" in sys_type:
        idf_content += """
    HVACTemplate:System:VAV, Main_VAV_Sys, Auto, Auto, Auto, Auto, Auto, Auto, Auto, ChilledWater;
    """

    idf_content += """
    Output:VariableDictionary, IDF;
    Output:Variable, *, Zone Mean Air Temperature, Hourly;
    Output:Variable, *, Zone Air System Sensible Heating Energy, Hourly;
    Output:Variable, *, Zone Air System Sensible Cooling Energy, Hourly;
    """

    try:
        if not os.path.exists("simulation"):
            os.makedirs("simulation")
        with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
            f.write(idf_content)
        print(f"\n✅ 成功生成: {OUTPUT_FILENAME}")
        print(f"✅ 路径: {os.path.abspath(OUTPUT_PATH)}")
        print("请务必打开这个新生成的文件进行测试!")
    except Exception as e:
        print(f"❌ 失败: {e}")


if __name__ == "__main__":
    run_conversion()
