import json
import os

def load_json(path):
    if os.path.exists(path):
        with open(path, 'r', encoding='utf-8') as f:
            return json.load(f)
    return {}

def set_location(city_name, model_dict):
    db = load_json("data/location_db.json")
    data = db.get(city_name)
    if data:
        model_dict["Location"] = data
        model_dict["Location"]["City"] = city_name
        return f"成功:已将地点设为 {city_name}。"
    else:
        return f"失败:数据库中没找到 {city_name} 的数据。"

def get_material_options(city_name):
    db = load_json("data/materials_db.json")
    data = db.get(city_name)
    if not data:
        return "无推荐数据,请自定义。"
    return f"""
    基于 {city_name},推荐方案如下:
    A. {data['Recommended']['name']} (U={data['Recommended']['u_value']}) - {data['Recommended']['desc']}
    B. {data['Economy']['name']} (U={data['Economy']['u_value']}) - {data['Economy']['desc']}
    """

def set_material_choice(city_name, choice_type, model_dict):
    db = load_json("data/materials_db.json")
    try:
        selected = db[city_name][choice_type]
        model_dict["Construction"] = selected
        return f"成功:已应用 {selected['name']}。"
    except:
        return "失败:选择无效。"

def set_schedule(building_type, model_dict):
    db = load_json("data/schedules_db.json")
    data = db.get(building_type)

    if data:
        model_dict["Schedule"] = data
        return f"成功：已应用 [{building_type}] 时间表模板。"
    else:
        return "失败：未知的建筑类型。"

# --- Tool 5: 设置空调系统 (HVAC) ---
def set_hvac(system_type, model_dict):
    db = load_json("data/hvac_db.json")
    hvac_data = db.get(system_type)

    if not hvac_data:
        return "失败：未知的空调系统类型。"

    # 关键逻辑：HVAC是依附于 Zone 的。
    # 我们需要遍历字典里的 Geometry -> Zones，给每个房间贴上空调标签。
    
    # 1. 检查有没有 Zone 信息 (防止报错)
    if "Geometry" not in model_dict or "Zones" not in model_dict["Geometry"]:
        # 如果还没做几何解析，我们先创建一个假的Zone列表演示一下
        zones = ["Zone_1", "Zone_2"] 
    else:
        zones = model_dict["Geometry"]["Zones"]
        
    # 2. 为每个 Zone 生成 HVAC 配置
    hvac_config = {
        "SystemType": hvac_data["type"],
        "Performance": hvac_data,
        "Applied_Zones": zones  # 记录应用到了哪些房间
    }
    
    model_dict["HVAC"] = hvac_config
    return f"成功：已为 {len(zones)} 个房间配置了 [{system_type}] 系统。"

def generate_idf_file(model_dict):
    """
    模拟生成 IDF 文件。
    实际项目中，这里会调用你的 Pydantic Converter。
    """
    file_name = "test_building.idf"
    
    # 这里我们简单地把字典转成字符串写入文件，假装它是IDF
    # 等你写好了真正的Converter，把下面这段替换掉即可
    idf_content = f"""! EnergyPlus IDF File Generated by Energy Agent
! Project Location: {model_dict.get('Location', {}).get('City')}
! Building Type: {model_dict.get('Schedule', {}).get('description')}

! --- Simulation Control ---
Version, 9.5;
Timestep, 6;

! --- Location ---
Site:Location,
  {model_dict.get('Location', {}).get('City', 'Unknown')}, 
  {model_dict.get('Location', {}).get('latitude', 0)},
  {model_dict.get('Location', {}).get('longitude', 0)},
  ...;

! --- Material & Construction ---
! Selected: {model_dict.get('Construction', {}).get('name')}
! U-Value: {model_dict.get('Construction', {}).get('u_value')}

! --- HVAC System ---
! Type: {model_dict.get('HVAC', {}).get('SystemType')}

! --- Zones ---
! (这里会循环写入 model_dict['Geometry']['Zones'] 里的内容)
"""
    
    # 写入本地文件
    with open(file_name, "w", encoding="utf-8") as f:
        f.write(idf_content)
        
    return file_name, idf_content